sudo: required
language: c
os:
  - linux
compiler:
  - gcc
addons:
apt:
  sources:
    - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
  packages:
    - cmake
    - cmake-data
before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update

install:
    - sudo apt-get install cmake
script:
  - sudo apt-get upgrade
  - cd VelocityRaptor
  - mkdir build
  - cd build
  - cmake ..
  - make
